### ISSUE TITLE
Slider for padding  with real time preview

### ISSUE THREAD

**Issue by omkar-tenkale** [omkar-tenkale/PicTools-IssueTracker#1]
For padding inputs instead of textbox,switch to slider which shows dynamic preview

Submitted on behalf of Bakli

**Comment by JonDous** [comment]
Yeah but the slider should be near, coz some people need to have ability to type specific number.
Slider helps to understand visually, meanwhile enter using keyboard is more exact for people who needs for printing, etc.

**Comment by omkar-tenkale** [comment]
The new preview option fairly eliminates this problem for user to set a value, see result, set new value etc trial and error experimentation

Also with time user is expected to get experienced with the tools
