### ISSUE TITLE
Compress PNG images

### ISSUE THREAD

**Issue by omkar-tenkale** [omkar-tenkale/PicTools-IssueTracker#6]
png supports compression levels

Submitted on behalf of Bakli

**Comment by omkar-tenkale** [comment]
PNG is lossless format and hence can't be compressed in android

https://stackoverflow.com/questions/39793619/is-there-any-way-to-reduce-png-size

**Comment by JonDous** [comment]
I know about lossless but png can be compressed. Is it problem of android's library? Maybe need to user another one?

**Comment by JonDous** [comment]
It called not compress it called optimize.

Many sites, plugins and software like https://tinypng.com/ can do it.
